package Samt.Spiro.Graphics;

import java.awt.Component;
import javax.swing.SwingUtilities;

/**
 *
 * @author Julian Cummaudo
 */
public class PointChoice extends javax.swing.JPanel {

    private Double value;

    /**
     * Creates new form CentralPointChoice
     */
    public PointChoice() {
        initComponents();
        initActions();
    }

    private void initActions() {
        //Percorro tutti i componenti
        for (Component component : getComponents()) {
            //se il componente attuale è un JButton
            if (component instanceof javax.swing.JButton){
                    
                //Se il bottone è dentro alla giusta toolbar allora fai cose
                if(SwingUtilities.getAncestorOfClass(javax.swing.JToolBar.class, component).equals(jToolBar1)){
                    ((javax.swing.JButton) component).addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            pcActionPerformed(evt);
                        }
                    });
                }else if(SwingUtilities.getAncestorOfClass(javax.swing.JToolBar.class, component).equals(jToolBar1)){
                    ((javax.swing.JButton) component).addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            //pmActionPerformed(evt);
                        }
                    });
                }
            }
        }

    }

    public Double getValue() {
        return value;
    }

    private void pcActionPerformed(java.awt.event.ActionEvent evt) {
        this.value = Double.parseDouble(evt.getActionCommand());
        //canvas1.setRadiusCenter(Double.parseDouble(evt.getActionCommand()));
        //canvas1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        Pc = new javax.swing.JButton();
        Pc30 = new javax.swing.JButton();
        Pc35 = new javax.swing.JButton();
        Pc40 = new javax.swing.JButton();
        Pc45 = new javax.swing.JButton();
        Pc50 = new javax.swing.JButton();
        Pc55 = new javax.swing.JButton();
        Pc60 = new javax.swing.JButton();
        Pc65 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        Pc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Pc.setText("Pc");
        Pc.setFocusable(false);
        Pc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pc.setPreferredSize(new java.awt.Dimension(53, 25));
        Pc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PcActionPerformed(evt);
            }
        });
        jToolBar1.add(Pc);

        Pc30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc30.setText("30");
        Pc30.setToolTipText("");
        Pc30.setFocusable(false);
        Pc30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pc30.setPreferredSize(new java.awt.Dimension(53, 25));
        Pc30.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Pc30);

        Pc35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc35.setText("35");
        Pc35.setToolTipText("");
        Pc35.setFocusable(false);
        Pc35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pc35.setPreferredSize(new java.awt.Dimension(53, 25));
        Pc35.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Pc35);

        Pc40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc40.setText("40");
        Pc40.setToolTipText("");
        Pc40.setFocusable(false);
        Pc40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pc40.setPreferredSize(new java.awt.Dimension(53, 25));
        Pc40.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Pc40);

        Pc45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc45.setText("45");
        Pc45.setToolTipText("");
        Pc45.setFocusable(false);
        Pc45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pc45.setPreferredSize(new java.awt.Dimension(53, 25));
        Pc45.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Pc45);

        Pc50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc50.setText("50");
        Pc50.setToolTipText("");
        Pc50.setFocusable(false);
        Pc50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pc50.setPreferredSize(new java.awt.Dimension(53, 25));
        Pc50.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Pc50);

        Pc55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc55.setText("55");
        Pc55.setToolTipText("");
        Pc55.setFocusable(false);
        Pc55.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pc55.setPreferredSize(new java.awt.Dimension(53, 25));
        Pc55.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Pc55);

        Pc60.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc60.setText("60");
        Pc60.setToolTipText("");
        Pc60.setFocusable(false);
        Pc60.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pc60.setPreferredSize(new java.awt.Dimension(53, 25));
        Pc60.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Pc60);

        Pc65.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc65.setText("65");
        Pc65.setToolTipText("");
        Pc65.setFocusable(false);
        Pc65.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pc65.setPreferredSize(new java.awt.Dimension(53, 25));
        Pc65.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(Pc65);

        add(jToolBar1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void PcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pc;
    private javax.swing.JButton Pc30;
    private javax.swing.JButton Pc35;
    private javax.swing.JButton Pc40;
    private javax.swing.JButton Pc45;
    private javax.swing.JButton Pc50;
    private javax.swing.JButton Pc55;
    private javax.swing.JButton Pc60;
    private javax.swing.JButton Pc65;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
