/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Samt.Spiro.Graphics;

/**
 *
 * @author julian.cummaudo
 */
public class Spirograph extends javax.swing.JFrame {

    /**
     * Creates new form Spirograph
     */
    public Spirograph() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pc = new javax.swing.JButton();
        Pm = new javax.swing.JButton();
        canvas1 = new Samt.Spiro.Graphics.Canvas();
        Pc30 = new javax.swing.JButton();
        Pc35 = new javax.swing.JButton();
        Pc45 = new javax.swing.JButton();
        Pc40 = new javax.swing.JButton();
        Pc50 = new javax.swing.JButton();
        Pc55 = new javax.swing.JButton();
        Pc60 = new javax.swing.JButton();
        Pc65 = new javax.swing.JButton();
        Pm65 = new javax.swing.JButton();
        Pm60 = new javax.swing.JButton();
        Pm55 = new javax.swing.JButton();
        Pm50 = new javax.swing.JButton();
        Pm85 = new javax.swing.JButton();
        Pm80 = new javax.swing.JButton();
        Pm75 = new javax.swing.JButton();
        Pm70 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Pc.setText("Pc");
        Pc.setPreferredSize(new java.awt.Dimension(53, 25));

        Pm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Pm.setText("Pm");

        javax.swing.GroupLayout canvas1Layout = new javax.swing.GroupLayout(canvas1);
        canvas1.setLayout(canvas1Layout);
        canvas1Layout.setHorizontalGroup(
            canvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        canvas1Layout.setVerticalGroup(
            canvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Pc30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc30.setText("30");
        Pc30.setToolTipText("");
        Pc30.setPreferredSize(new java.awt.Dimension(53, 25));
        Pc30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pc30ActionPerformed(evt);
            }
        });

        Pc35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc35.setText("35");
        Pc35.setToolTipText("");
        Pc35.setPreferredSize(new java.awt.Dimension(53, 25));

        Pc45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc45.setText("45");
        Pc45.setToolTipText("");
        Pc45.setPreferredSize(new java.awt.Dimension(53, 25));

        Pc40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc40.setText("40");
        Pc40.setToolTipText("");
        Pc40.setPreferredSize(new java.awt.Dimension(53, 25));

        Pc50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc50.setText("50");
        Pc50.setToolTipText("");
        Pc50.setPreferredSize(new java.awt.Dimension(53, 25));

        Pc55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc55.setText("55");
        Pc55.setToolTipText("");
        Pc55.setPreferredSize(new java.awt.Dimension(53, 25));

        Pc60.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc60.setText("60");
        Pc60.setToolTipText("");
        Pc60.setPreferredSize(new java.awt.Dimension(53, 25));

        Pc65.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pc65.setText("65");
        Pc65.setToolTipText("");
        Pc65.setPreferredSize(new java.awt.Dimension(53, 25));
        Pc65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pc65ActionPerformed(evt);
            }
        });

        Pm65.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pm65.setText("65");
        Pm65.setToolTipText("");
        Pm65.setPreferredSize(new java.awt.Dimension(53, 25));

        Pm60.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pm60.setText("60");
        Pm60.setToolTipText("");
        Pm60.setPreferredSize(new java.awt.Dimension(53, 25));

        Pm55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pm55.setText("55");
        Pm55.setToolTipText("");
        Pm55.setPreferredSize(new java.awt.Dimension(53, 25));

        Pm50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pm50.setText("50");
        Pm50.setToolTipText("");
        Pm50.setPreferredSize(new java.awt.Dimension(53, 25));

        Pm85.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pm85.setText("85");
        Pm85.setToolTipText("");
        Pm85.setPreferredSize(new java.awt.Dimension(53, 25));

        Pm80.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pm80.setText("80");
        Pm80.setToolTipText("");
        Pm80.setPreferredSize(new java.awt.Dimension(53, 25));

        Pm75.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pm75.setText("75");
        Pm75.setToolTipText("");
        Pm75.setPreferredSize(new java.awt.Dimension(53, 25));

        Pm70.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Pm70.setText("70");
        Pm70.setToolTipText("");
        Pm70.setPreferredSize(new java.awt.Dimension(53, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pc30, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pc35, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pc40, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pc45, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pc50, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pc55, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pc60, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pc65, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Pm, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pm50, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pm55, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pm60, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pm65, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Pm70, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Pm75, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Pm80, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Pm85, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pm)
                            .addComponent(Pc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pc30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pc35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pc40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pc45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pc50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pc55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pc60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pc65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pm50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pm55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pm60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pm65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pm70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pm75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pm80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pm85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 173, Short.MAX_VALUE))
                    .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void Pc30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pc30ActionPerformed
        canvas1.setRadiusCenter(Double.parseDouble(evt.getActionCommand()));
    }//GEN-LAST:event_Pc30ActionPerformed

    private void Pc65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pc65ActionPerformed
        canvas1.setRadiusCenter(Double.parseDouble(evt.getActionCommand()));
    }//GEN-LAST:event_Pc65ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Spirograph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Spirograph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Spirograph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Spirograph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Spirograph().setVisible(true);
            }
        });
    }
    // <editor-fold defaultstate="collapsed" desc="JButton">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pc;
    private javax.swing.JButton Pc30;
    private javax.swing.JButton Pc35;
    private javax.swing.JButton Pc40;
    private javax.swing.JButton Pc45;
    private javax.swing.JButton Pc50;
    private javax.swing.JButton Pc55;
    private javax.swing.JButton Pc60;
    private javax.swing.JButton Pc65;
    private javax.swing.JButton Pm;
    private javax.swing.JButton Pm50;
    private javax.swing.JButton Pm55;
    private javax.swing.JButton Pm60;
    private javax.swing.JButton Pm65;
    private javax.swing.JButton Pm70;
    private javax.swing.JButton Pm75;
    private javax.swing.JButton Pm80;
    private javax.swing.JButton Pm85;
    private Samt.Spiro.Graphics.Canvas canvas1;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
}
